http:
  routers:
    allBackendRouter:
      rule: Host(`localhost`)
      service: allbackends
  services:
    allbackends:
      loadBalancer:
        servers:
          - url: "http://localhost:1111"
          - url: "http://localhost:2222"
          - url: "http://localhost:3333"
