http:
  routers:
    allBackendRouter:
      rule: "Host(`localhost`) && PATH(`/`)"
      service: allbackends
    backendone:
      rule: "Host(`localhost`) && PATH(`/one`)"
      service: backendone
    backendtwo:
      rule: "Host(`localhost`) && PATH(`/two`)"
      service: backendtwo
  services:
    backendone:
        loadBalancer:
          servers:
            - url: "http://localhost:1111"
            - url: "http://localhost:2222"
    backendtwo:
      loadBalancer:
        servers:
          - url: "http://localhost:3333"
    allbackends:
      loadBalancer:
        servers:
          - url: "http://localhost:1111"
          - url: "http://localhost:2222"
          - url: "http://localhost:3333"
