# Static configuration
entryPoints:
    unsecure:
      address: :80

providers:
  file: 
    # filename: split-config-traefik.yaml
    # filename: blocadmin-config-traefik.yaml
    filename: wrr.yaml
    watch: true